---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-postgres
  namespace: sonarqube
  labels:
    app: postgres
spec:
  storageClassName: managed-nfs-storage-120
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
