---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-sonar-extensions
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 10Gi